### ISSUE TITLE
Rumor has it - Rumor Code Watcher creates a lag spike upon first use? Then most game movement is extremely stuttery from then on.

### ISSUE THREAD

**Issue by CullyDC** [emipa606/RoumorHasIt#3]
![20240818073705_1](https://github.com/user-attachments/assets/637f9b37-a11e-4217-9381-f54ba03321bd)
Here is from my save and most other saves where seemingly there is enough pawns to trigger it (possibly something related to clique or defecting code?) and also there has been enough time to have rumors start up (I don't know if my pawns have a huge rumor history or something that causes it too?) As shown, this is the only time dubs performance analyzer actually picks up this tick, but the effects are now present until quitting to main menu, reloading the save. The game (camera and pawns) is quite stuttery, even in pause, even in 1x speed... TPS is mostly unaffected, you can 3x and 2x totally fine...
![lag spike area](https://github.com/user-attachments/assets/75f69b81-a4f4-4fa4-87f3-9b45145519f3)
Just want to say before any of this code analysis that: I have no idea how to do .dll modding or editing in Rimworld Code. At all. I've done some .xml editing for many mods and generally have gotten good at figuring out bugs but this is out of my depth. Basically I just straight up removed the: 'MapComponentTick() : void 06000014' using dnSpy and literally just right click > delete.

Obviously this is not a great fix. But my save works fine, no lag spike and then also no stutter present anymore, pawns are still using the Rumor has it mod to spread rumors and apologise for them ect... So I came here to hopefully see if there is a more elegant solution. Any ideas? Thanks for any sort of help or response. Just want to also say, Thanks for all the great work in the rimworld modding community with the (continued) series.

Edit: Man I forgot to mention this at all. But I'm playing version 1.2 of Rimworld and all mods, a very handcrafted (400-500?) modlist that is built for compatibility (almost no errors in console, most errors can be fixed with debug tool anyway).

**Comment by emipa606** [comment]
I will look into it but be aware that I only change the code for the latest game version if I find some solution.

**Comment by emipa606** [comment]
After reviewing this I cannot really include it as it will remove some functionality from the mod.
